from . import legal_procedure_type
from . import legal_procedure_phase
from . import legal_procedure_step
from . import legal_procedure_field
from . import legal_procedure_transition
from . import legal_doc_requirement
from . import legal_fee_rule
from . import legal_sla_rule
from . import legal_poa
from . import legal_action_log
from . import legal_case
from . import legal_case_subject
from . import legal_case_document
from . import legal_case_check
from . import legal_fee
from . import legal_obligation
from . import legal_correspondence
from . import legal_dashboard
