{
    "name": "Legal Department - Contracts",
    "summary": "العقود والاتفاقيات - the contract register: lifecycle, parties, "
    "obligations, amendments and the signed document filed in the permanent register",
    "description": """
Legal Department - Contracts (العقود والاتفاقيات)
==================================================

The contract lifecycle, built the way an Iraqi legal department actually runs
one: a draft arrives, it is reviewed, negotiated, approved internally, sent to
the other side, signed, and only then does it become نافذ. Every one of those is
a state the file stands in, gated so that the same clerk who drafts a contract
cannot also grant it internal approval and only the manager may فسخ it.

Three decisions carry the design, and each is borrowed in concept - never in
code - from the OCA agreement/contract modules, which are AGPL-3 and therefore
re-implemented here rather than copied.

**Obligations are dated rows, not prose.** A payment clause that says "on the
first of every month" becomes a schedule that materialises a row per period,
generated by a job that is idempotent by a unique index on
(obligation, period, company). "Did we invoice for March" is then answered by a
record with a state - filed, late, waived - rather than by the absence of one,
which is indistinguishable from nobody having looked.

**An amendment never edits the contract in place.** A ملحق is its own record
with its own date, description and value change; the original terms stay exactly
as they were signed, and the contract's *current* value is the original plus the
applied amendments. Overwriting the value is how a department loses the ability
to answer "what did we actually sign", which is the only question a dispute
turns on.

**The signed contract is filed once, in the permanent register.** When a
contract is signed the PDF is written into ``legal.document`` - the company's one
register of dated artefacts - so an expiring contract raises the same renewal
alert as an expiring licence, on the same board, rather than in a silo of its
own.
""",
    "version": "19.0.1.0.0",
    "category": "Services/Legal",
    "license": "LGPL-3",
    "author": "Legal Department",
    "depends": ["legal_correspondence"],
    "data": [
        "security/ir.model.access.csv",
        "security/legal_contract_rules.xml",
        "data/legal_contract_sequence.xml",
        "data/legal_contract_type_data.xml",
        "views/legal_contract_type_views.xml",
        "views/legal_contract_obligation_views.xml",
        "views/legal_contract_modification_views.xml",
        "views/legal_contract_views.xml",
        "wizard/legal_contract_sign_views.xml",
        "views/legal_correspondence_origin_views.xml",
        "views/legal_contract_menus.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
