{
    "name": "Legal Department - Procedures",
    "summary": "The procedure engine: configurable steps, checklists, fees, deadlines and the file that walks them",
    "description": """
Legal Department - Procedures (المعاملات)
==========================================

The spine of the product. One transactional model - ``legal.case`` (المعاملة) -
walks a state machine that is **data, not code**: ``step_id`` is a foreign key
into ``legal.procedure.step``, and a procedure is added by configuring rows
rather than by writing a Python class per ministry.

Three decisions carry the whole design.

**The state machine is configuration.** A strictly linear procedure - and most
Iraqi procedures are linear until something goes wrong - needs *zero*
transition rows: the engine synthesises the advance from ``sequence``. Explicit
``legal.procedure.transition`` rows exist only for the interesting moves: the
branch, the return for correction, the rejection, the referral to another
directorate. That inversion is what keeps a fifty-step براءة ذمة walk
configurable by a consultant instead of by a developer.

**A procedure has a version, and a live file stays bound to the one it started
under.** Iraqi practice changes by circular, sometimes with a fortnight's
notice. A file opened in March under the old fee schedule must keep printing
the old fee, so ``legal.case.procedure_version`` is a snapshot taken at open
time and the type carries ``effective_from`` / ``effective_to`` /
``superseded_by_id`` rather than being edited in place.

**A deadline is a row with a state, never a computed absence.** "Have we filed
social security for March" cannot be answered by the absence of a record -
absence is indistinguishable from nobody having looked. ``legal.obligation.instance``
is a dated row per period, generated by a cron that is idempotent by a unique
index on (schedule, period, company), so re-running it creates nothing.
""",
    "version": "19.0.1.0.0",
    "category": "Services/Legal",
    "license": "LGPL-3",
    "author": "Legal Department",
    "depends": ["legal_core", "legal_correspondence"],
    "data": [
        "security/legal_procedure_security.xml",
        "security/ir.model.access.csv",
        "security/legal_procedure_rules.xml",
        "data/legal_procedure_data.xml",
        "data/legal_procedure_cron.xml",
        "views/legal_procedure_type_views.xml",
        "views/legal_procedure_step_views.xml",
        "views/legal_procedure_transition_views.xml",
        "views/legal_doc_requirement_views.xml",
        "views/legal_fee_views.xml",
        "views/legal_sla_views.xml",
        "views/legal_poa_views.xml",
        "views/legal_obligation_views.xml",
        "views/legal_case_views.xml",
        "views/legal_action_log_views.xml",
        "wizard/legal_case_return_views.xml",
        "wizard/legal_case_step_views.xml",
        "views/legal_correspondence_origin_views.xml",
        "views/legal_procedure_menus.xml",
        "views/legal_dashboard_views.xml",
    ],
    "assets": {
        # One glob rather than a list: the components are small and split by
        # responsibility, and adding one should never require a manifest edit.
        "web.assets_backend": [
            "legal_procedure/static/src/components/**/*",
        ],
        "web.assets_unit_tests": [
            "legal_procedure/static/tests/**/*.test.js",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
