# Part of the DMA Accreditation module. See LICENSE file for full copyright and licensing details.
"""The accreditation dossier: one file, in the order an auditor reads it.

The evidence of an accreditation is scattered across the record the way it is
scattered across a paper file - prerequisites on the checklist, the SOP on its
own tab, receipts under the fees, minutes with the committee decision, the
letter and the certificate generated by the workflow. Any one of them is easy
to find. "Show me the complete evidence and decision trail for DMA/ACC/2026/
0042" is not.

This assembles exactly that, once, from the record itself:

* an **index**, which every consumer shares - the panel on the form, the
  printed cover sheet and the archive all read the same structure, so they can
  never disagree about what the dossier contains;
* a **printed index** (a QWeb report in the same bilingual house style as the
  letter and the certificate);
* a **downloadable archive**, built on demand and never stored - so a dossier
  costs no second copy of a single byte - carrying that same index as its cover
  sheet in HTML, because an officer waiting on a download should not be waiting
  on a PDF engine.

Security
--------
The dossier never takes a list of attachment ids from the client. It derives
the list from the record, after the reader has been checked against the record,
and then filters it again through ``ir.attachment``'s own access rules, so a
reader who may not see one piece of evidence gets a dossier without it rather
than an error - and never gets a piece of evidence from another file.

Archive entry names are sanitised with ``odoo.tools.osutil.clean_filename`` and
de-duplicated. Odoo's own ZIP builders (``mail``'s ``_make_zip``, ``account``'s
``_build_zip_from_attachments``) write the attachment name into the archive
verbatim, which lets an applicant called their file ``../../evil.exe`` write
outside the extraction directory on a careless extractor. That is not repeated
here.
"""
import io
import logging
import zipfile

from odoo import api, fields, models
from odoo.exceptions import UserError
from odoo.tools import osutil

from .dma_constants import role_label, state_label

_logger = logging.getLogger(__name__)

#: Ceiling on the size of a generated archive. Every ZIP builder in Odoo core
#: buffers the whole thing in memory, and so does this one, so an accreditation
#: carrying half a gigabyte of scans must fail loudly rather than take the
#: worker down with it.
DOSSIER_MAX_BYTES_PARAMETER = "dma_accreditation.dossier_max_bytes"
DOSSIER_MAX_BYTES_DEFAULT = 200 * 1024 * 1024

#: ``ir.attachment.description`` marker written on the documents the workflow
#: generates, so the dossier can name them without matching translated text.
OFFICE_LETTER_MARKER = "dma_office_letter"
CERTIFICATE_MARKER = "dma_certificate"


class DmaAccreditationRequest(models.Model):
    _inherit = "dma.accreditation.request"

    office_letter_attachment_id = fields.Many2one(
        "ir.attachment", string="Office Accreditation Letter", readonly=True,
        copy=False, ondelete="set null",
    )
    certificate_attachment_id = fields.Many2one(
        "ir.attachment", string="Operational Certificate File", readonly=True,
        copy=False, ondelete="set null",
    )
    dossier_payload = fields.Json(
        string="Dossier", compute="_compute_dossier_payload",
        depends_context=("lang", "uid"),
    )
    dossier_document_count = fields.Integer(
        string="Documents in the Dossier", compute="_compute_dossier_counts",
    )
    dossier_missing_count = fields.Integer(
        string="Missing Evidence", compute="_compute_dossier_counts",
    )

    # ==================================================================
    # Remembering what the workflow generated
    # ==================================================================
    def _generate_report_attachment(self, report_xmlid, filename):
        """Keep a handle on the official documents the workflow produces.

        They are the two pieces of the dossier the Directorate issues itself,
        and matching them back out of the chatter by their (translated) file
        name would break the moment somebody works in Arabic.
        """
        attachment = super()._generate_report_attachment(report_xmlid, filename)
        if not attachment:
            return attachment
        marker, field = {
            "dma_accreditation.action_report_office_letter": (
                OFFICE_LETTER_MARKER, "office_letter_attachment_id",
            ),
            "dma_accreditation.action_report_certificate": (
                CERTIFICATE_MARKER, "certificate_attachment_id",
            ),
        }.get(report_xmlid, (False, False))
        if marker:
            attachment.sudo().write({"description": marker})
            self.sudo().write({field: attachment.id})
        return attachment

    # ==================================================================
    # The index
    # ==================================================================
    def _dossier_entry(self, attachment, label, meta=False, superseded=False):
        return {
            "attachment_id": attachment.id,
            "name": attachment.name,
            "label": label,
            "mimetype": attachment.mimetype or "",
            "size": attachment.file_size or 0,
            "date": fields.Datetime.to_string(attachment.create_date),
            "meta": meta or "",
            "superseded": superseded,
        }

    def _dossier_readable_attachments(self):
        """Every attachment of this file the current reader is allowed to see.

        Derived from the record, never from the client, and then run through
        ``ir.attachment``'s own access rules so a reader who is not entitled to
        one piece of evidence simply does not get it.
        """
        self.ensure_one()
        Attachment = self.env["ir.attachment"]
        # Reached through this record's own relations, so they belong to it by
        # construction - including the ones an officer uploaded before the line
        # was saved, which carry no res_id at all.
        candidates = Attachment.browse()
        candidates |= self.document_ids.attachment_ids
        candidates |= self.document_ids.submission_ids.attachment_ids
        candidates |= self.sudo().sop_attachment_ids
        candidates |= self.sudo().committee_minutes_ids
        candidates |= self.fee_ids.attachment_ids
        # Plus whatever was filed against the request itself: the letter, the
        # certificate and any correspondence dropped in the chatter.
        candidates |= Attachment.sudo().search([
            ("res_model", "=", self._name), ("res_id", "=", self.id),
        ])
        candidates = Attachment.browse(candidates.exists().ids)

        # The reader's own rights come first, and they have to: reading so much
        # as the ``res_model`` of an attachment the reader may not see raises,
        # so any inspection of the set has to happen on what survives this.
        # Somebody who is not entitled to one piece of evidence gets a dossier
        # without it rather than an error.
        allowed = candidates._filtered_access("read")

        # Belt and braces against a future refactor smuggling a foreign file
        # in: an attachment filed against *another* accreditation can never be
        # part of this dossier, however it got into the set above.
        foreign = allowed.filtered(
            lambda att: att.res_model == self._name and att.res_id != self.id
        )
        if foreign:
            _logger.warning(
                "DMA dossier of %s: dropped %s attachment(s) belonging to "
                "another accreditation file", self.display_name, len(foreign),
            )
            allowed -= foreign
        return allowed

    def _dossier_index(self):
        """The dossier, as a list of sections. One reading, shared by all.

        The order is the order the sections are listed in on a paper file: who
        applied, what they submitted, what they paid, what the committee said,
        and what the Directorate issued.
        """
        self.ensure_one()
        readable = set(self._dossier_readable_attachments().ids)

        def visible(attachments):
            return attachments.filtered(lambda att: att.id in readable)

        sections = []

        # -- 1. The application itself ---------------------------------
        sections.append({
            "key": "application",
            "label": self.env._("Application"),
            "entries": [],
            "note": self.env._(
                "The accreditation file summary is generated with the dossier."
            ),
            "generated": True,
        })

        # -- 2. Prerequisites, one block per requirement ----------------
        prerequisites = []
        for line in self.document_ids.sorted(lambda doc: (doc.sequence, doc.id)):
            entries = [
                self._dossier_entry(
                    attachment, line.type_id.display_name,
                    meta=self.env._("version %s", line.version),
                )
                for attachment in visible(line.attachment_ids)
            ]
            for submission in line.submission_ids.sorted("version"):
                entries.extend(
                    self._dossier_entry(
                        attachment, line.type_id.display_name,
                        meta=self.env._("version %s", submission.version),
                        superseded=True,
                    )
                    for attachment in visible(submission.attachment_ids)
                )
            prerequisites.append({
                "key": line.type_id._dossier_folder(),
                "document_id": line.id,
                "label": line.type_id.display_name,
                "required": line.is_required,
                "satisfied": line._is_satisfied(),
                "review_result": line.review_result,
                "review_label": dict(
                    line._fields["review_result"]._description_selection(self.env)
                ).get(line.review_result, ""),
                "validity_state": line.validity_state,
                "validity_label": dict(
                    line._fields["validity_state"]._description_selection(self.env)
                ).get(line.validity_state, ""),
                "expiry_date": fields.Date.to_string(line.expiry_date) or "",
                "reviewer": line.reviewed_by.display_name or "",
                "reviewed_on": fields.Datetime.to_string(line.reviewed_on) or "",
                "version": line.version,
                "blocking_reason": line.blocking_reason or "",
                "entries": entries,
            })
        sections.append({
            "key": "prerequisites",
            "label": self.env._("Prerequisite Documents"),
            "documents": prerequisites,
            "entries": [entry for block in prerequisites for entry in block["entries"]],
        })

        # -- 3. SOP -----------------------------------------------------
        sections.append({
            "key": "sop",
            "label": self.env._("Standing Operating Procedures"),
            "note": " ".join(filter(None, [
                self.sop_reference or "",
                self.env._("version %s", self.sop_version) if self.sop_version else "",
            ])),
            "entries": [
                self._dossier_entry(attachment, self.env._("Electronic SOP"))
                for attachment in visible(self.sudo().sop_attachment_ids)
            ],
        })

        # -- 4. Fees ----------------------------------------------------
        fee_entries = []
        fee_labels = dict(
            self.env["dma.fee.payment"]._fields["fee_type"]._description_selection(self.env)
        )
        for fee in self.fee_ids.sorted("id"):
            label = "%s%s" % (
                fee_labels.get(fee.fee_type, ""),
                " - %s" % fee.receipt_number if fee.receipt_number else "",
            )
            fee_entries.extend(
                self._dossier_entry(
                    attachment, label,
                    meta=fields.Date.to_string(fee.receipt_date) or "",
                )
                for attachment in visible(fee.attachment_ids)
            )
        sections.append({
            "key": "fees",
            "label": self.env._("Fee Receipts"),
            "entries": fee_entries,
        })

        # -- 5. Committee -----------------------------------------------
        sections.append({
            "key": "committee",
            "label": self.env._("Accreditation Committee"),
            "note": fields.Date.to_string(self.committee_date) or "",
            "entries": [
                self._dossier_entry(attachment, self.env._("Committee Minutes"))
                for attachment in visible(self.sudo().committee_minutes_ids)
            ],
        })

        # -- 6. What the Directorate issued ------------------------------
        issued = self.env["ir.attachment"].browse()
        issued |= self.office_letter_attachment_id
        issued |= self.certificate_attachment_id
        sections.append({
            "key": "issued",
            "label": self.env._("Documents Issued by the Directorate"),
            "entries": [
                self._dossier_entry(
                    attachment,
                    self.env._("Office Accreditation Letter")
                    if attachment == self.office_letter_attachment_id
                    else self.env._("Operational Accreditation Certificate"),
                )
                for attachment in visible(issued)
            ],
        })

        # -- 7. Everything else that was filed against the request -------
        accounted = {
            entry["attachment_id"]
            for section in sections for entry in section.get("entries", [])
        }
        others = self.env["ir.attachment"].sudo().search([
            ("res_model", "=", self._name), ("res_id", "=", self.id),
        ])
        sections.append({
            "key": "correspondence",
            "label": self.env._("Other Correspondence and Evidence"),
            "entries": [
                self._dossier_entry(attachment, attachment.name)
                for attachment in visible(others)
                if attachment.id not in accounted
            ],
        })

        # -- 8. The decision trail ---------------------------------------
        sections.append({
            "key": "history",
            "label": self.env._("Decision Trail"),
            "entries": [],
            "generated": True,
            "history": [{
                "step": state_label(self.env, visit["step"]),
                "role": role_label(self.env, visit["role"]) if visit["role"] else "",
                "user": visit["user"] or "",
                "entered_on": fields.Datetime.to_string(visit["entered_on"]) or "",
                "left_on": fields.Datetime.to_string(visit["left_on"]) or "",
                "duration": self._format_hours(visit["hours"]),
                "decision": visit["decision"] or "",
                "open": visit["open"],
            } for visit in self._process_visits()],
        })
        return sections

    @api.depends(
        "document_ids.attachment_ids", "document_ids.review_result",
        "document_ids.submission_ids", "sop_attachment_ids",
        "committee_minutes_ids", "fee_ids.attachment_ids",
        "office_letter_attachment_id", "certificate_attachment_id",
        "state", "approval_line_ids",
    )
    def _compute_dossier_payload(self):
        rtl = self.env["res.lang"]._lang_get(
            self.env.lang or "en_US"
        ).direction == "rtl"
        for request in self:
            sections = request._dossier_index()
            request.dossier_payload = {
                "rtl": rtl,
                "reference": request.name,
                "partner": request.partner_id.display_name,
                "state_label": state_label(self.env, request.state),
                "sections": sections,
                "file_count": sum(
                    len(section.get("entries", [])) for section in sections
                ),
                "missing": [
                    block["label"] for block in next(
                        (s for s in sections if s["key"] == "prerequisites"), {},
                    ).get("documents", [])
                    if block["required"] and not block["satisfied"]
                ],
            }

    @api.depends("dossier_payload")
    def _compute_dossier_counts(self):
        for request in self:
            payload = request.dossier_payload or {}
            request.dossier_document_count = payload.get("file_count", 0)
            request.dossier_missing_count = len(payload.get("missing", []))

    # ==================================================================
    # The archive
    # ==================================================================
    def _dossier_filename(self):
        """A safe, stable base name: ``DMA_ACC_2026_0042``."""
        self.ensure_one()
        return osutil.clean_filename((self.name or "dossier").replace("/", "_"))

    def _dossier_max_bytes(self):
        raw = self.env["ir.config_parameter"].sudo().get_param(
            DOSSIER_MAX_BYTES_PARAMETER, DOSSIER_MAX_BYTES_DEFAULT,
        )
        try:
            return max(int(raw), 1)
        except (TypeError, ValueError):
            return DOSSIER_MAX_BYTES_DEFAULT

    def _dossier_zip_bytes(self):
        """Build the archive in memory, with sanitised, unique entry names.

        Bytes are read through the ORM, which sanitises the filestore path
        itself - no path is ever built here.
        """
        self.ensure_one()
        self.check_access("read")
        sections = self._dossier_index()
        readable = self._dossier_readable_attachments()
        by_id = {attachment.id: attachment for attachment in readable}

        total = sum(attachment.file_size or 0 for attachment in readable)
        ceiling = self._dossier_max_bytes()
        if total > ceiling:
            raise UserError(self.env._(
                "The evidence of %(request)s totals %(size)s MB, more than the "
                "%(max)s MB an accreditation dossier may be built from in one "
                "go. Download the tabs separately, or raise the limit in the "
                "system parameters.",
                request=self.display_name,
                size=round(total / (1024 * 1024), 1),
                max=round(ceiling / (1024 * 1024), 1),
            ))

        root = self._dossier_filename()
        buffer = io.BytesIO()
        used = set()

        def unique(path):
            """Never let two documents of the same name shadow one another."""
            if path not in used:
                used.add(path)
                return path
            stem, dot, extension = path.rpartition(".")
            stem, extension = (stem, "." + extension) if dot else (path, "")
            index = 2
            while "%s (%s)%s" % (stem, index, extension) in used:
                index += 1
            candidate = "%s (%s)%s" % (stem, index, extension)
            used.add(candidate)
            return candidate

        with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for number, section in enumerate(sections, start=1):
                folder = "%02d_%s" % (number, osutil.clean_filename(section["key"]))
                for block in section.get("documents", []):
                    for entry in block["entries"]:
                        attachment = by_id.get(entry["attachment_id"])
                        if not attachment:
                            continue
                        path = "/".join(part for part in (
                            root, folder, osutil.clean_filename(block["key"]),
                            "superseded" if entry["superseded"] else "",
                            osutil.clean_filename(attachment.name or "document"),
                        ) if part)
                        self._dossier_write(archive, attachment, unique(path))
                if section.get("documents"):
                    continue
                for entry in section.get("entries", []):
                    attachment = by_id.get(entry["attachment_id"])
                    if not attachment:
                        continue
                    self._dossier_write(archive, attachment, unique("/".join([
                        root, folder, osutil.clean_filename(attachment.name or "document"),
                    ])))
            # The cover sheet goes in last so it is written even when the file
            # carries no evidence at all - an empty dossier is still a dossier,
            # and its index is the part that says what is missing.
            index = self._dossier_index_document()
            if index:
                archive.writestr(unique("%s/00_%s_index.html" % (root, root)), index)
        return buffer.getvalue()

    def _dossier_write(self, archive, attachment, path):
        """Add one attachment to the archive, tolerating a file that has gone.

        Read through the ``raw`` field rather than through ``ir.binary``: that
        service builds an HTTP stream and resolves the filestore path against
        the *current request*, so it only works inside a controller - and a
        dossier is also assembled from a scheduled job and from a test. The ORM
        field sanitises the filestore path itself, so nothing is given up.
        """
        try:
            archive.writestr(
                path, attachment.raw or b"", compress_type=zipfile.ZIP_DEFLATED,
            )
        except Exception:  # noqa: BLE001 - one lost file must not lose the dossier
            _logger.warning(
                "DMA dossier: could not read attachment %s of %s",
                attachment.id, self.display_name, exc_info=True,
            )

    def _dossier_index_document(self):
        """The cover sheet that goes into the archive, as HTML.

        HTML and not PDF, deliberately. The archive is built while an officer
        waits on a download, and rendering this same template through
        wkhtmltopdf costs a minute on a plain server - the engine starts a
        browser - against ten milliseconds for the markup. The reader opens the
        index in the browser they already have; when they want a *printed*
        cover sheet, the Print Index button renders the very same template to
        PDF, where waiting for a print is what everybody expects.

        It also means the archive has an index on a server with no PDF engine
        at all, which is where the module is most likely to be installed.
        """
        self.ensure_one()
        try:
            content, _content_type = self.env.ref(
                "dma_accreditation.action_report_dossier_index"
            ).sudo()._render_qweb_html(
                "dma_accreditation.action_report_dossier_index", self.ids,
            )
            return content
        except Exception:  # noqa: BLE001 - a cover sheet must never lose a dossier
            _logger.warning(
                "DMA dossier: could not render the index of %s", self.display_name,
                exc_info=True,
            )
            return False

    # ==================================================================
    # Actions
    # ==================================================================
    def action_download_dossier(self):
        """Hand the reader the archive, through the access-checked route."""
        self.ensure_one()
        self.check_access("read")
        return {
            "type": "ir.actions.act_url",
            "target": "self",
            "url": "/dma/accreditation/dossier/%s" % self.id,
        }

    def action_print_dossier_index(self):
        return self.env.ref(
            "dma_accreditation.action_report_dossier_index"
        ).report_action(self)
