from . import legal_engine
from . import legal_expiry_mixin
from . import legal_jurisdiction
from . import legal_gov_body
from . import legal_entity
from . import legal_signatory
from . import legal_document_type
from . import legal_document
from . import res_company
